apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythonsample
  labels:
    app: pythonsample
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pythonsample
  template:
    metadata:
      labels:
        app: pythonsample
    spec:
      containers:
      - name: pythonsample
        image:nee1234/samplepython:v2
        ports:
        - containerPort: 8080
