apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythonsample
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image:nee1234/samplepython:v2
        ports:
        - containerPort: 8080
